from crewai import Agent, Task, Crew, Process
from langchain_community.llms.ollama import Ollama
from textwrap import dedent
from langchain.agents import tool
import os
import json

os.environ["OPENAI_API_KEY"] = "NA"

llm = Ollama(model="llama3.1")
num_iter = 1

def call_back(output: str):
    with open("callback_resp.txt", 'w') as file:
        file.write(output)

# class SaveOutput:
#     @tool
#     def save_to_file(llm_response: str):
#         """Save your JSON response here after each iteration"""
#         with open("llm_response.txt", 'w') as file:
#             file.write(llm_response)
#         return "File Saved"

#     def tools():
#         return [SaveOutput.save_to_file]
        
@tool
def save_to_file(llm_response: str):
    """Save your JSON response here after each iteration"""
    with open("validation_resp.txt", 'w') as file:
        file.write(llm_response)
    return "File Saved"

def validate_output(output):
    expected_keys = ["agenda", "summary", "discussion"]
    if all(key in output for key in expected_keys) and isinstance(output["discussion"], list):
        for discussion in output["discussion"]:
            if not all(key in discussion for key in ["discussion_point", "person_responsible", "completion_date", "remarks"]):
                return False
        return True
    return False

class ValidationAgent:
    @tool
    def validate_and_save(output: str):
        """Validate the Note-Taker Agent's responses, and save them here if valid. Return an error, if the format is invalid."""
        output = json.loads(output)
        if validate_output(output):
            with open("validated_response.json", "w") as file:
                json.dump(output, file, indent=4)
            return "Output is valid and saved to 'validated_response.json'"
        else:
            return "Output is invalid"

    def tools():
        return [ValidationAgent.validate_and_save]

# Agent to extract agenda
note_taker = Agent(
    role="Professional Note-Taker for a Meeting",
    goal=f"""Extract the agenda, summary, and discussion points from meeting transcripts. Return your thought-out output after each iteration, and use the SaveOutput tool to store that output in a file.
            The Validation Agent will be validating your responses. Act exactly on that agent's requirements. Mention your name before each response, and exit the loop when either:
            - The validation agent is satisfied,
            - When you've looped over {num_iter} times
            - When the other agent sends an exit message. 
            Send a message to the other agent before exiting. Save each response of your iteration in a local file.""",
    backstory=dedent("""You are a note-taker for meetings. You are always handed out meeting transcripts, which are sometimes
                        easier to understand, but sometimes they make no sense. This is due to the fact that they are directly 
                        transcribed from audio to text, which does result in a lot of transcription issues due to a difference in accents, distance from the microphone, etc.
                        You need to decipher, judging by the context of the meeting and using your LLM reasoning, whether the dialogue mentioned in the script was truly spoken by the said person
                        or was it just a mere transcription error. You also need to filter out any explicit content that's spoken in the meetings. All in all, expect the transcript to be
                        senseless, and derive context out of it. That is your job to do! Also, you'll be working with a Validation Agent who'll be monitoring and validating your responses."""),
    verbose=True,     
    tools=[save_to_file],           
    llm=llm
)

# Validation Agent
validation_agent = Agent(
    role="Validation Agent",
    goal=f"""Compare the past meeting transcript, and the past response, with the current meeting transcript, and its response (generated by the Note-Taker Agent), and give remarks to the Note-Taker Agent accordingly.
            Your job is to validate the Note-Taker Agent's responses according to the past meeting content. Remind the Note-Taker Agent to save the response to a local file using its provided tools.
            Exit the loop once you're satisfied with the Note-Taker Agent's Response, or when you've reached {num_iter} iterations,
            or when the other agent sends an exit message. Send a message to the other agent before exiting.""",
    backstory=dedent("""You are a validator for the Meeting Note-Taker Agent. As the meeting transcripts are transcribed from audio to text, there is a high chance of transcription errors in the
                        transcript, due to which the meeting report may be affected. Therefore, you'll be provided with a transcript of a past meeting, its desired output, and the transcript of the current meeting
                        to validate the responses of the Note-Taker Agent."""),
    verbose=True,
    tools=ValidationAgent.tools(),
    llm=llm
)

# Sample meeting transcript
meeting_transcript = "Here is the sample meeting transcript..."
with open('/Users/sulaiman/Desktop/transcript.txt', 'r') as file:
    meeting_transcript = file.read()

# Task for Note-Taker Agent
task = Task(
    description=f""""Extract the agenda, summary, and discussion points from the following meeting transcript. 
            Mention your name before each response, and exit the loop when either:
            - The validation agent is satisfied,
            - When you've looped over {num_iter} times
            - When the other agent sends an exit message. 
           Send a message to the other agent before exiting. Save each response of your iteration in a local file as per the tool given to you.
                    {meeting_transcript}""",
    agent=note_taker,
    output_file='llm_response.txt',
    expected_output="""A JSON object of the following format. For example, if you have the output for summary, you should
                        insert your output in <the-summary> after "summary". The parenthesis mentions the word/line limit for each output.
                        Write "-" in front of any field who's data is unavailable.  
                        Save the output for each iteration to a file.
                        Mention the file name where you saved the data: 
                        {
                            "agenda": <the-agenda> (one line),
                            "summary": <the-summary> (300 words),
                            "discussion": [
                                {
                                    "discussion_point": <discussion_point>,
                                    "person_responsible": <person_responsible>,
                                    "completion_date": <completion_date>,
                                    "remarks": <the_remarks>
                                },
                                {
                                    "discussion_point": "It was suggested to use a recursive approach to boost context, where the response is passed as input and then answered recursively.",
                                    "person_responsible": "-",
                                    "completion_date": <completion_date>,
                                    "remarks": <the_remarks>
                                },
                                {
                                    "discussion_point": "Another option mentioned was using API endpoints to improve the chatbot.",
                                    "person_responsible": "-",
                                    "completion_date": <completion_date>,
                                    "remarks": <the_remarks>
                                }
                            ]
                        }
                        """
)


with open('/Applications/Documents/Project_2_Meeting_Minutes/that_meeting.txt', 'r') as file:
    past_transcript = file.read()

with open('past_response.txt', 'r') as file:
    past_response = file.read()

# Task for Validation Agent
validation_task = Task(
    description=f"""Validate the response from the Note-Taker Agent using to the past meeting transcript, and its desired response, with the current meeting transcript, and the Note-Taker Agent's generated response.
                    Ensure that the Note-Taker agent provides a 300 word summary. Remind the Note-Taker Agent to save the response to a local file using its provided tools. Exit the loop once you're satisfied with the Note-Taker Agent's Response, or when you've reached {num_iter} iterations,
                    or when the other agent sends an exit message. Send a message to the other agent before exiting.
                    Past Meeting Transcript: {past_transcript},
                    Past Meeting Response: {past_response},
                    Current Meeting Transcript: {meeting_transcript}""",
    agent=validation_agent
)

crew = Crew(
    agents=[note_taker, validation_agent],
    tasks=[task, validation_task]
)

print("starting")
result = crew.kickoff()

print("\n\ndone:\n\n")
print(result)